### ISSUE TITLE
After compiling this version and starting the android version this error it is popping up.

### ISSUE THREAD

**Issue by viorel8** [lavrinec/Angular-Project-Template#1]
An uncaught Exception occurred on "main" thread.
Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Cannot compile /data/user/0/org.nativescript.sassproject/files/app/bundle.js
SyntaxError: Unexpected identifier
File: (file:///data/user/0/org.nativescript.sassproject/files/app/bundle.js:326:144)

StackTrace: 
require(:1:266)

SyntaxError: Unexpected identifier

StackTrace:
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Cannot compile /data/user/0/org.nativescript.sassproject/files/app/bundle.js
SyntaxError: Unexpected identifier
File: (file:///data/user/0/org.nativescript.sassproject/files/app/bundle.js:326:144)

StackTrace: 
require(:1:266)

SyntaxError: Unexpected identifier
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6567)
	at android.app.ActivityThread.access$1300(ActivityThread.java:231)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7478)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: com.tns.NativeScriptException: Cannot compile /data/user/0/org.nativescript.sassproject/files/app/bundle.js
SyntaxError: Unexpected identifier
File: (file:///data/user/0/org.nativescript.sassproject/files/app/bundle.js:326:144)

StackTrace: 
require(:1:266)

SyntaxError: Unexpected identifier
	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:674)
	at com.tns.Runtime.run(Runtime.java:666)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6562)
	... 8 more

**Comment by maticbezjak** [comment]
We know about that error. The current stable branch is v8-electron . We are still figuring out the problems with NativeScript and Angular 9. The NativeScript team is saying that if you do this steps you can make it work but for me the solution was unsuccessful. (https://github.com/NativeScript/nativescript-angular/wiki/Updating-and-developing-for-@nativescript-angular-v9-with-Ivy-or-without)
